#!/usr/bin/env bash
set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

tests/scripts/test-notifications
tests/scripts/docker-config
tests/scripts/docker-build-notification-services
tests/scripts/docker-up-notification-services
tests/scripts/docker-smoke-notification-services
